apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-crabe
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: webapp=ghcr.io/crabe-etsmtl/crabe-atelier:latest,mysql=ghcr.io/crabe-etsmtl/crabe-mysql:latest
    argocd-image-updater.argoproj.io/webapp.update-strategy: digest
    argocd-image-updater.argoproj.io/mysql.update-strategy: digest
    argocd-image-updater.argoproj.io/webapp.pull-secret: pullsecret:argocd/ghcr-secret
    argocd-image-updater.argoproj.io/mysql.pull-secret: pullsecret:argocd/ghcr-secret
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-crabe
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: apps/crabe/webApp/prod
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
