apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubSecretEngineRole
metadata:
  name: test-grav
spec:
  authentication: 
    path: kubernetes
    role: config-admin
  path: github
  repositories:
  - test.test.t
  organizationName: ClubCedille
