apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  source:
    repoURL: https://github.com/ClubCedille/Plateforme-Cedille
    path: system/external-dns/resources
    targetRevision: HEAD 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true