apiVersion: dns.gcp.upbound.io/v1beta1
kind: RecordSet
metadata:
  name: staging-dns-record
spec:
  forProvider:
    name: staging.kustomizetest
    managedZoneRef:
      name: omni.cedille.club
    ttl: 3600
    type: "A"