apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml
  - dns.yaml

patches:
  - path: patch.yaml

# host: staging.fdjivhsifgn.cedille.club

# Define common and environment-specific configuration here