apiVersion: v1
kind: Service
metadata:
  name: discord-provider-service
spec:
  selector:
    app: discord-provider
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000