name: Markdown lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'wiki/**'
    types:
      - opened
      - synchronize

jobs:
  markdown-repo-standards:
    uses:
      clubcedille/cedille-workflows/.github/workflows/markdown-lint.yml@master
