name: Markdown lint

on:
  workflow_call:
  pull_request:
    paths:
      - 'wiki/**'
    types:
      - opened
      - synchronize

jobs:
  kubernetes-repo-standards:
    uses:
      clubcedille/cedille-workflows/.github/workflows/kubernetes-repo-standards.yml@master
